FROM node:20-alpine AS development

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000 5555

CMD [ "sh", "-c", "chmod +x /app/start-dev.sh && /app/start-dev.sh" ]
