apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: collector-backend:local
          imagePullPolicy: Never # Important pour utiliser l'image locale buildée dans Minikube
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service.collector.svc.cluster.local:5432/collector?schema=public"
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: collector
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
